// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzy9bcGAPhspcf2fcFLRwaF_ZKAE5UUQU',
    appId: '1:291187022026:web:ecad97978e3aa0ccd37c33',
    messagingSenderId: '291187022026',
    projectId: 'showndeal-bc8f7',
    authDomain: 'showndeal-bc8f7.firebaseapp.com',
    storageBucket: 'showndeal-bc8f7.appspot.com',
    measurementId: 'G-WLYYQ1QFZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXS9TwDYHHT42L0IWQeX2hxTebFDB5yE',
    appId: '1:291187022026:android:245455c99a7e40a9d37c33',
    messagingSenderId: '291187022026',
    projectId: 'showndeal-bc8f7',
    storageBucket: 'showndeal-bc8f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvh-eqyU9bWo9k9caTFjSWgJHXG_5uuc',
    appId: '1:291187022026:ios:c6165c425c7b5303d37c33',
    messagingSenderId: '291187022026',
    projectId: 'showndeal-bc8f7',
    storageBucket: 'showndeal-bc8f7.appspot.com',
    iosClientId: '291187022026-9t4jb4kmeht4c7d74vu6mg5jtu83aoeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.snd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvh-eqyU9bWo9k9caTFjSWgJHXG_5uuc',
    appId: '1:291187022026:ios:c6165c425c7b5303d37c33',
    messagingSenderId: '291187022026',
    projectId: 'showndeal-bc8f7',
    storageBucket: 'showndeal-bc8f7.appspot.com',
    iosClientId: '291187022026-9t4jb4kmeht4c7d74vu6mg5jtu83aoeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.snd',
  );
}
